### ISSUE TITLE
Demo uses CommonCrypto and that isn't in Podfile

### ISSUE THREAD

**Issue by bbookman** [rubygarage/authorize-me#10]
> authorize-me-master/Core/Common/Extensions/String+Hashing.swift:10:8: No such module 'CommonCrypto'

//  String+Hashing.swift
//  Authorizer
//
//  Created by Radislav Crechet on 5/8/17.
//  Copyright © 2017 RubyGarage. All rights reserved.
//

import Foundation
import CommonCrypto

..........

**Comment by plzen** [comment]
Could you provide more details?
Which iOS, provider, device or simulator have you used?

**Comment by bbookman** [comment]
The code above is directly from your repo. 
the code has

“Import CommonCrypto”

The Podfile does not. A quick search for String-Hashing.Swift or CommonCrypto in this very repo should get you everything you need. 

What am I missing?

**Comment by radyslavkrechet** [comment]
It was fixed in version 1.2.2
