### ISSUE TITLE
#selector' refers to instance method 'cancel()' that is not exposed to Objective-C

### ISSUE THREAD

**Issue by bbookman** [rubygarage/authorize-me#4]
> AuthorizeMe/Core/Controllers/ProviderController.swift:46:86: Argument of '#selector' refers to instance method 'cancel()' that is not exposed to Objective-C

The dev can fix this and xCode supplies a fix, however I suggest fixing it in your code.

> Add '@objc' to expose this instance method to Objective-C

**Comment by plzen** [comment]
Now library is supporting only Swift 3. You can switch to Swift 3.2 for AuthorizeMe pod in Build Settings and try to compile app again.

We will release Swift 4 support soon.

**Comment by plzen** [comment]
New release with Swift 4 support have just been submitted to CocoaPods https://cocoapods.org/pods/AuthorizeMe

**Comment by bbookman** [comment]
Did the following and still see the same issue:
1.  pod cache clean -- all
2. pod repo --update
3.  Add Authorize me to Podfile
4. pod install
5. open my project and build

Same exact error as before.  This is due to the fact that you need to add @objc statements I believe

"Add '@objc' to expose this instance method to Objective-C'

**Comment by bbookman** [comment]
Here is the fix

    **@objc** func cancel() {
        complete(withUrl: nil, error: AuthorizeError.cancel)
    }

**Comment by plzen** [comment]
Thank you, @bbookman. We added this as fix https://github.com/rubygarage/authorize-me/blob/master/Core/Controllers/ProviderController.swift#L56
